version: '3'

services:
  ep-postgres:
    image: postgres:15
    container_name: ep-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - "15432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_init.sql

    restart: always
    networks:
      - EP-BD

  server:
    build: ./backend
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/usr/app
    networks:
      - EP-BD
    depends_on:
      - ep-postgres
    environment:
      DB_DATABASE: mydb
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: ep-postgres
      DB_PORT: 5432
    links:
      - ep-postgres

  
  front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    networks:
      - EP-BD
    environment:
      DB_DATABASE: mydb
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: ep-postgres
      DB_PORT: 5432
    links:
      - server

volumes:
  db:
    driver: local

networks:
  EP-BD:
    driver: bridge
